### ISSUE TITLE
Package links to npmjs.com can be wrong

### ISSUE THREAD

**Issue by redox** [algolia/yarnpkg-website#1]
We link to `npmjs.com/<package-name>` but we should link to `npmjs.com/package/<package-name>`.

 - https://github.com/yarnpkg/website/pull/322/files#diff-d47536a005af642c7d7777bfa3177960R85
 - https://github.com/yarnpkg/website/pull/322/files#diff-d47536a005af642c7d7777bfa3177960R191

cc @bobylito

**Comment by bobylito** [comment]
https://github.com/yarnpkg/website/commit/a9cf111c49df3dddb12b1d0b6ebc18931c173555 cc @redox

**Comment by vvo** [comment]
was merged
