### ISSUE TITLE
OpenSearch no more working

### ISSUE THREAD

**Issue by vvo** [algolia/yarnpkg-website#14]
Typing "yarn [TAB] lodash" is no more working in my google chrome.

Redirects to https://www.yarnpkg.com/packages?q=lodash which then fails and redirect to /en/packages.

**Comment by Haroenv** [comment]
You must have an old cache or something, I can’t replicate it 😕

**Comment by vvo** [comment]
@Haroenv I think you did find the root cause for this, can you show how to solve it and provide the doc that says it's cached internally by browsers the first time it's used? For reference.
