### ISSUE TITLE
Last commit date discrepancy

### ISSUE THREAD

**Issue by rayrutjes** [algolia/yarnpkg-website#18]
I just pushed a new package to NPM, and here is what I see on the detailed page:

![image](https://cloud.githubusercontent.com/assets/5570853/25141251/4affdd9e-2463-11e7-90db-ffb2781f1c13.png)

> Last commit 51 weeks ago

**Comment by Haroenv** [comment]
I think I'm reading the GitHub stats in the wrong direction: https://api.github.com/repos/rayrutjes/diffable-html/stats/commit_activity shows the commits as being in the last week of the JSON.

**Comment by Haroenv** [comment]
relevant code: https://github.com/algolia/yarnpkg-website/blob/master/js/src/lib/Details/Activity.js#L7-L35

**Comment by Haroenv** [comment]
I think I found the source of the bug, it has to do with the `.reverse()`, but I have to wait until GitHub allows me to do some more requests 😄
