### ISSUE TITLE
Search page's title is missing

### ISSUE THREAD

**Issue by redox** [algolia/yarnpkg-website#2]
We probably forgot to define a var before the `|`.

![screen shot 2017-01-02 at 12 05 29](https://cloud.githubusercontent.com/assets/29529/21588110/c3ce7286-d0e3-11e6-8fcc-83bdf5240080.png)

**Comment by vvo** [comment]
Was done: https://github.com/yarnpkg/website/commit/c64386cf7a0e3068d9011f3e9f81699ff907fa05
