### ISSUE TITLE
Display the deprecation message for packages

### ISSUE THREAD

**Issue by vvo** [algolia/yarnpkg-website#20]
I think it's good that we are still showing deprecated packages, because it adds context and one's deprecated package may be central to someone else software.

Still, with every deprecation comes a handy message that is shown in console. We should also display it on the website. The information seems to be in npm: https://twitter.com/vvoyer/status/868913200607219712

**Comment by Haroenv** [comment]
It is already shown, but not a lot are deprecated actually. Check the https://yarnpkg.com/en/package/algolia for example

**Comment by vvo** [comment]
https://yarnpkg.com/en/package/babel

This should show that:

![image](https://cloud.githubusercontent.com/assets/123822/26561358/fb58f0a2-44bd-11e7-90e9-4657a3e1ad35.png)

**Comment by Haroenv** [comment]
It is showing as deprecated though

Maybe it should be more visible than a badge? 

<img width="642" alt="screen shot 2017-05-29 at 22 29 04" src="https://cloud.githubusercontent.com/assets/6270048/26561380/3de1262e-44be-11e7-92ea-ace257bb0224.png">

Or do you want the message too, could be useful.

**Comment by vvo** [comment]
Yes I do want us to display the message, because that's the interesting part, to know where to look for new adventure :D

**Comment by Haroenv** [comment]
Heh, just checked, and the message is already what is in the deprecated field in our index. How should it be shown, as `title` initially, but how else?

**Comment by vvo** [comment]
This can be closed

**Comment by vvo** [comment]
(Sorry I thought this was the yarn repo otherwise I would have closed it..:D)
