### ISSUE TITLE
Additional trailing comma in list of tags

### ISSUE THREAD

**Issue by dzello** [algolia/yarnpkg-website#3]
<img width="277" alt="screenshot 2017-01-10 13 13 35" src="https://cloud.githubusercontent.com/assets/174777/21826342/f118b7ca-d73b-11e6-9d8d-84978e5f12f2.png">

**Comment by Haroenv** [comment]
I think this is fixed

![screen shot 2017-02-07 at 16 01 57](https://cloud.githubusercontent.com/assets/6270048/22696579/d4d66e12-ed4e-11e6-8b7c-04e32eb7fb10.png)
